/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUserDashboardRouteImport } from './routes/_user/user-dashboard'
import { Route as UserNewTicketRouteImport } from './routes/_user/new-ticket'
import { Route as LoginSignupRouteImport } from './routes/_login/signup'
import { Route as LoginLogoutRouteImport } from './routes/_login/logout'
import { Route as LoginLoginRouteImport } from './routes/_login/login'
import { Route as UserTicketsTicketIdRouteImport } from './routes/_user/tickets/$ticketId'
import { Route as UserSubmitTicketSubmitTicketRouteImport } from './routes/_user/_submitTicket/submitTicket'
import { Route as AdminStatusTicketStatusTicketRouteImport } from './routes/_admin/_statusTicket/statusTicket'
import { Route as AdminReportReportRouteImport } from './routes/_admin/_report/report'
import { Route as AdminProblemsSubmitTypesProblemRouteImport } from './routes/_admin/_problems/submitTypesProblem'
import { Route as AdminDashboardDashboardRouteImport } from './routes/_admin/_dashboard/dashboard'
import { Route as AdminCustomerCustomerRegistrationRouteImport } from './routes/_admin/_customer/customerRegistration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserDashboardRoute = UserUserDashboardRouteImport.update({
  id: '/_user/user-dashboard',
  path: '/user-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UserNewTicketRoute = UserNewTicketRouteImport.update({
  id: '/_user/new-ticket',
  path: '/new-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSignupRoute = LoginSignupRouteImport.update({
  id: '/_login/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginLogoutRoute = LoginLogoutRouteImport.update({
  id: '/_login/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginLoginRoute = LoginLoginRouteImport.update({
  id: '/_login/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserTicketsTicketIdRoute = UserTicketsTicketIdRouteImport.update({
  id: '/_user/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSubmitTicketSubmitTicketRoute =
  UserSubmitTicketSubmitTicketRouteImport.update({
    id: '/_user/_submitTicket/submitTicket',
    path: '/submitTicket',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminStatusTicketStatusTicketRoute =
  AdminStatusTicketStatusTicketRouteImport.update({
    id: '/_admin/_statusTicket/statusTicket',
    path: '/statusTicket',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReportReportRoute = AdminReportReportRouteImport.update({
  id: '/_admin/_report/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProblemsSubmitTypesProblemRoute =
  AdminProblemsSubmitTypesProblemRouteImport.update({
    id: '/_admin/_problems/submitTypesProblem',
    path: '/submitTypesProblem',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardDashboardRoute = AdminDashboardDashboardRouteImport.update({
  id: '/_admin/_dashboard/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomerCustomerRegistrationRoute =
  AdminCustomerCustomerRegistrationRouteImport.update({
    id: '/_admin/_customer/customerRegistration',
    path: '/customerRegistration',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginLoginRoute
  '/logout': typeof LoginLogoutRoute
  '/signup': typeof LoginSignupRoute
  '/new-ticket': typeof UserNewTicketRoute
  '/user-dashboard': typeof UserUserDashboardRoute
  '/customerRegistration': typeof AdminCustomerCustomerRegistrationRoute
  '/dashboard': typeof AdminDashboardDashboardRoute
  '/submitTypesProblem': typeof AdminProblemsSubmitTypesProblemRoute
  '/report': typeof AdminReportReportRoute
  '/statusTicket': typeof AdminStatusTicketStatusTicketRoute
  '/submitTicket': typeof UserSubmitTicketSubmitTicketRoute
  '/tickets/$ticketId': typeof UserTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginLoginRoute
  '/logout': typeof LoginLogoutRoute
  '/signup': typeof LoginSignupRoute
  '/new-ticket': typeof UserNewTicketRoute
  '/user-dashboard': typeof UserUserDashboardRoute
  '/customerRegistration': typeof AdminCustomerCustomerRegistrationRoute
  '/dashboard': typeof AdminDashboardDashboardRoute
  '/submitTypesProblem': typeof AdminProblemsSubmitTypesProblemRoute
  '/report': typeof AdminReportReportRoute
  '/statusTicket': typeof AdminStatusTicketStatusTicketRoute
  '/submitTicket': typeof UserSubmitTicketSubmitTicketRoute
  '/tickets/$ticketId': typeof UserTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_login/login': typeof LoginLoginRoute
  '/_login/logout': typeof LoginLogoutRoute
  '/_login/signup': typeof LoginSignupRoute
  '/_user/new-ticket': typeof UserNewTicketRoute
  '/_user/user-dashboard': typeof UserUserDashboardRoute
  '/_admin/_customer/customerRegistration': typeof AdminCustomerCustomerRegistrationRoute
  '/_admin/_dashboard/dashboard': typeof AdminDashboardDashboardRoute
  '/_admin/_problems/submitTypesProblem': typeof AdminProblemsSubmitTypesProblemRoute
  '/_admin/_report/report': typeof AdminReportReportRoute
  '/_admin/_statusTicket/statusTicket': typeof AdminStatusTicketStatusTicketRoute
  '/_user/_submitTicket/submitTicket': typeof UserSubmitTicketSubmitTicketRoute
  '/_user/tickets/$ticketId': typeof UserTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/new-ticket'
    | '/user-dashboard'
    | '/customerRegistration'
    | '/dashboard'
    | '/submitTypesProblem'
    | '/report'
    | '/statusTicket'
    | '/submitTicket'
    | '/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/new-ticket'
    | '/user-dashboard'
    | '/customerRegistration'
    | '/dashboard'
    | '/submitTypesProblem'
    | '/report'
    | '/statusTicket'
    | '/submitTicket'
    | '/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/_login/login'
    | '/_login/logout'
    | '/_login/signup'
    | '/_user/new-ticket'
    | '/_user/user-dashboard'
    | '/_admin/_customer/customerRegistration'
    | '/_admin/_dashboard/dashboard'
    | '/_admin/_problems/submitTypesProblem'
    | '/_admin/_report/report'
    | '/_admin/_statusTicket/statusTicket'
    | '/_user/_submitTicket/submitTicket'
    | '/_user/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginLoginRoute: typeof LoginLoginRoute
  LoginLogoutRoute: typeof LoginLogoutRoute
  LoginSignupRoute: typeof LoginSignupRoute
  UserNewTicketRoute: typeof UserNewTicketRoute
  UserUserDashboardRoute: typeof UserUserDashboardRoute
  AdminCustomerCustomerRegistrationRoute: typeof AdminCustomerCustomerRegistrationRoute
  AdminDashboardDashboardRoute: typeof AdminDashboardDashboardRoute
  AdminProblemsSubmitTypesProblemRoute: typeof AdminProblemsSubmitTypesProblemRoute
  AdminReportReportRoute: typeof AdminReportReportRoute
  AdminStatusTicketStatusTicketRoute: typeof AdminStatusTicketStatusTicketRoute
  UserSubmitTicketSubmitTicketRoute: typeof UserSubmitTicketSubmitTicketRoute
  UserTicketsTicketIdRoute: typeof UserTicketsTicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/user-dashboard': {
      id: '/_user/user-dashboard'
      path: '/user-dashboard'
      fullPath: '/user-dashboard'
      preLoaderRoute: typeof UserUserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/new-ticket': {
      id: '/_user/new-ticket'
      path: '/new-ticket'
      fullPath: '/new-ticket'
      preLoaderRoute: typeof UserNewTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login/signup': {
      id: '/_login/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LoginSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login/logout': {
      id: '/_login/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LoginLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_login/login': {
      id: '/_login/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/tickets/$ticketId': {
      id: '/_user/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof UserTicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/_submitTicket/submitTicket': {
      id: '/_user/_submitTicket/submitTicket'
      path: '/submitTicket'
      fullPath: '/submitTicket'
      preLoaderRoute: typeof UserSubmitTicketSubmitTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/_statusTicket/statusTicket': {
      id: '/_admin/_statusTicket/statusTicket'
      path: '/statusTicket'
      fullPath: '/statusTicket'
      preLoaderRoute: typeof AdminStatusTicketStatusTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/_report/report': {
      id: '/_admin/_report/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AdminReportReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/_problems/submitTypesProblem': {
      id: '/_admin/_problems/submitTypesProblem'
      path: '/submitTypesProblem'
      fullPath: '/submitTypesProblem'
      preLoaderRoute: typeof AdminProblemsSubmitTypesProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/_dashboard/dashboard': {
      id: '/_admin/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/_customer/customerRegistration': {
      id: '/_admin/_customer/customerRegistration'
      path: '/customerRegistration'
      fullPath: '/customerRegistration'
      preLoaderRoute: typeof AdminCustomerCustomerRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginLoginRoute: LoginLoginRoute,
  LoginLogoutRoute: LoginLogoutRoute,
  LoginSignupRoute: LoginSignupRoute,
  UserNewTicketRoute: UserNewTicketRoute,
  UserUserDashboardRoute: UserUserDashboardRoute,
  AdminCustomerCustomerRegistrationRoute:
    AdminCustomerCustomerRegistrationRoute,
  AdminDashboardDashboardRoute: AdminDashboardDashboardRoute,
  AdminProblemsSubmitTypesProblemRoute: AdminProblemsSubmitTypesProblemRoute,
  AdminReportReportRoute: AdminReportReportRoute,
  AdminStatusTicketStatusTicketRoute: AdminStatusTicketStatusTicketRoute,
  UserSubmitTicketSubmitTicketRoute: UserSubmitTicketSubmitTicketRoute,
  UserTicketsTicketIdRoute: UserTicketsTicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
